TRUE               1
FALSE              0
SYNC               0
ASYNC              1
FAKE               13579

DEFAULT_DEST      "Internet"

3G_AP             "Internet"
3G_AP2            "Internet2"
WLAN_AP           "Wlan"
WLAN_AP2          "Wlan2"
EMULATOR_AP       "Ethernet with Daemon Dynamic IP"
BAD_AP            "BadIap" // CIptvTestUtilities::GetIapIdL returns AP that does not work
INVALID_AP        "invalidiap" // CIptvTestUtilities::GetIapIdL returns invalid AP ID
